### ISSUE TITLE
KThread relies on unittest package

### ISSUE THREAD

**Issue by baugarten** [baugarten/cs162#9]
We cannot submit unittest to the autograder so it doesn't compile.

Please remove the dependency

**Comment by ducky64** [comment]
While someone takes care of that on the repo, can you just remove the dependency locally for submission?

**Comment by mqphan** [comment]
I move the test for join inside KThead.java. joinTest does not depend on
JUnit anymore
Minh

**Comment by mqphan** [comment]
Someone please resubmit, thanks

**Comment by baugarten** [comment]
Minh, you have the remove the dependency on the test.unittest package because we don't submit that

You most definitely didn't fix it on master

**Comment by mqphan** [comment]
I only changed the KThread.java file in the join_con branch. I deleleted
all imports from test.unittest, moved all the code of joinTest.java into
KThread, so there is no dependency. Do I miss any else?
Minh
